# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Energy Meter PDF
version: "0.0.1"
slug: EMPDF
description:  Energy Meter PDF add-on
url: "https://github.com/Chauron/ha-addons/tree/main/energy-meter-pdf"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false

